### ISSUE TITLE
Missing files during npm install

### ISSUE THREAD

**Issue by LLLOOOMMM** [justin-guan/discord-doggo#28]
Hello,

during the setup of discord-doggo I get the following errors when executing `npm install`. Its the same in an elavated cli aswell an an not elevated cli.
If installed `msvc` and python using the command `npm i -g windows-build-tools`.

There are lots of warnings about missing files.

Im am running W10 20H2 with node.js v14.16.0 and Python 2.7.15

Details are in the log below.
[2021-03-22T19_39_20_680Z-debug.log](https://github.com/justin-guan/discord-doggo/files/6184932/2021-03-22T19_39_20_680Z-debug.log)

If you need more logs or informaiton, I will trys to provide it.

Regards,
Max

**Comment by justin-guan** [comment]
This error is saying that npm could not find the `erlpack` dependency. This should be because you don't have git installed since this dependency is the only one that resolves via git instead of the npm repository. If you don't have [git](https://git-scm.com/) installed, try installing it and then running `npm install` again. When adding that dependency, I kind of just assumed that anyone trying to use this would have git installed because this was distributed through github and built with git as the version control system.

Additionally, if you never installed git, then I suggest that you clone this repo instead of just downloading it after installing git. Cloning it will allow you to pull down any changes without redownloading the whole repo again.

**Comment by justin-guan** [comment]
I ran through a clean build from scratch on Windows earlier today, and made some updates in #29. FWIW, I did end up adding git as a requirement in the README, and I still think that the issue in your log is related to git not being installed. But I think I've also fixed any issues related to building on Windows too now. Let me know how it's working for you now.

**Comment by justin-guan** [comment]
Hi @LLLOOOMMM, is this still giving you trouble? Or is everything working now? I'm happy to help further if needed, but otherwise I'd like to close this issue.

**Comment by LLLOOOMMM** [comment]
Hey,
thanks for your patience. I didn't get around to installing git until today. After I installed it, this error disappeared. 
Thanks again for your help 👍
